let dados = [

 {
    titulo : "Banoffee",
    descrição : "O banoffee é uma deliciosa sobremesa de origem inglesa que conquistou o paladar de muitas pessoas ao redor do mundo.",
    link : "https://www.instagram.com/p/C_IvbAFRix8/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
},
{
    titulo: "bolo de cenoura",
    descrição: "Clássico da confeitaria, o bolo de cenoura é úmido e saboroso, perfeito para qualquer ocasião.",
    link: "https://www.instagram.com/p/C-21CwURU3l/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" // Substitua por um link para uma imagem ou receita do bolo de cenoura
    
},
{
    titulo: "brownie",
    descrição: "O brownie é uma sobremesa de chocolate americana, com textura densa e úmida, perfeita para os amantes de chocolate.",
    link: "https://www.instagram.com/p/C3do1E0vi9Z/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" // Substitua por um link para uma imagem ou receita do brownie
}
]
